# docker-compose.yml
version: '3.8'

services:
  datarex:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env
    environment:
      - DEBUG=${DEBUG}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Фронтенд (опционально)
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"